easy_admin:
    design:
        assets:
            css:
                - 'build/easy_admin.css'
            js:
                - 'build/runtime.js'
                - 'build/easy_admin.js'


        menu:
            - entity: Calculation
            - entity: User
              permission: ROLE_USER_ADMIN

    edit:
        actions: ['-delete']

    list:
        actions: ['search', '-delete']

    entities:
        Calculation:
            class: App\Entity\Calculation
            controller: App\Controller\CalculationController

            list:
                actions:
                    - name: 'run'
                      label: 'Calculate'
                    - name: show
                    - name: edit
                      permission: ROLE_CALCULATION_ADMIN

                fields:
                    - property: name
                    - property: calculator
                    # - property: createdBy
                    - property: createdAt
                    # - property: updatedBy
                    - property: updatedAt

            form:
                fields:
                    - property: name
                    - property: calculator
                      type: App\Form\Type\CalculatorType
#                    - property: calculatorSettings
#                      type: App\Form\Type\CalculatorSettingsType

        User:
            class: App\Entity\User
            controller: ItkDev\UserManagementBundle\Controller\UserController

            list:
                actions:
                    - name: 'impersonate'
                      permission: ROLE_ALLOWED_TO_SWITCH

                fields:
                    - property: email
                    # - property: createdBy
                    - property: createdAt
                    # - property: updatedBy
                    - property: updatedAt

            new:
                fields:
                    - property: email
                    - property: roles
                      type: ItkDev\UserManagementBundle\Form\Type\UserRolesType

            edit:
                fields:
                    - property: email
                    - property: enabled
                    - property: roles
                      type: ItkDev\UserManagementBundle\Form\Type\UserRolesType
