easy_admin:
    design:
        assets:
            css:
                - 'build/easy_admin.css'
            js:
                - 'build/runtime.js'
                - 'build/easy_admin.js'

    entities:
        Calculation:
            class: App\Entity\Calculation
            controller: App\Controller\CalculationController

            list:
                actions:
                    - name: show
                    - name: 'run'
                      label: 'Calculate'

                fields:
                    - property: name
                    - property: calculator
                    - property: createdBy
                    - property: createdAt
                    - property: updatedAt

            form:
                fields:
                    - property: name
                    - property: calculator
                      type: App\Form\Type\CalculatorType
#                    - property: calculatorSettings
#                      type: App\Form\Type\CalculatorSettingsType

        User:
            class: App\Entity\User

            list:
                fields:
                    - property: username
                    - property: createdBy
                    - property: createdAt
                    - property: updatedAt
